 version: "3.7"

 services:
    postgresql:
      image: postgres:latest
      #restart: always
      volumes:
        - ./postgresql/data:/var/lib/postgresql/data
        - ./postgresql/initdb.d:/docker-entrypoint-initdb.d
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: example
        POSTGRES_DB: visa_sponsorship_search
